import { db } from './src/core/db.js';
import { playerSignalRows } from './src/news/indexer.js';
const rows = await playerSignalRows(db, 10);
console.log('players with signal rows:', rows.size);
for (const [uid, r] of [...rows].slice(0, 5)) console.log(uid, r);
const links = await db('news_player_map as m').join('players as p','p.uid','m.player_uid').where('m.news_id', 269).select('p.web_name');
console.log('item 269 links:', links.map((l) => l.web_name).join(', '));
const item = await db('news_items').where('id', 269).first('signals','story_id','source_tier','fetched_at');
console.log('item 269:', item);
await db.destroy();
